# Generated by Django 4.2.27 on 2026-01-21 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0002_remove_farm_antibiotic_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antibiotic_name', models.CharField(max_length=100)),
                ('reason', models.CharField(choices=[('treat_disease', 'Treat Disease'), ('prophylactic', 'Prophylactic'), ('other', 'Other')], max_length=20)),
                ('treated_for', models.CharField(choices=[('enteric', 'Enteric'), ('respiratory', 'Respiratory'), ('reproductive', 'Reproductive'), ('other', 'Other')], max_length=20)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='farms.farm')),
            ],
        ),
    ]
