# Generated by Django 4.2.27 on 2026-02-25 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_dataoperator'),
        ('treatments', '0002_treatment_status_treatment_vet'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments_recorded', to='users.user'),
        ),
    ]
