# Generated by Django 4.2.27 on 2026-02-26 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0009_bulk_flock_and_treatment_levels'),
        ('treatments', '0003_treatment_recorded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='animal',
            field=models.ForeignKey(blank=True, help_text='If set, treatment targets a single animal in the flock', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments', to='farms.animal'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='flock',
            field=models.ForeignKey(blank=True, help_text='If set, treatment targets this flock only', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments', to='farms.flock'),
        ),
    ]
