# Generated by Django 4.2.27 on 2026-02-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0004_bulk_flock_and_treatment_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='dosage',
            field=models.CharField(blank=True, help_text='e.g. 5ml, 250mg', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='method_intake',
            field=models.CharField(blank=True, help_text='e.g. Oral, Injection, Feed', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='vet_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
