# Generated by Django 4.2.27 on 2026-03-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0005_treatment_dosage_treatment_method_intake_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='safe_harvest_date',
            field=models.DateField(blank=True, help_text='AI-predicted or manually set safe harvest date', null=True),
        ),
    ]
