# Generated by Django 4.2.27 on 2026-01-26 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AntimicrobialFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='molecules', to='reference_data.antimicrobialfamily')),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tissue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MRLLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrl_mgkg', models.FloatField()),
                ('molecule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_data.molecule')),
                ('species_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_data.speciesgroup')),
                ('tissue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_data.tissue')),
            ],
            options={
                'unique_together': {('molecule', 'species_group', 'tissue')},
            },
        ),
        migrations.CreateModel(
            name='MoleculeSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('molecule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_data.molecule')),
                ('species_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_data.speciesgroup')),
            ],
            options={
                'unique_together': {('molecule', 'species_group')},
            },
        ),
    ]
