# Generated by Django 4.2.27 on 2026-02-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrllimit',
            name='withdrawal_days',
            field=models.IntegerField(blank=True, help_text='Standard withdrawal period in days', null=True),
        ),
    ]
