# Generated by Django 4.2.27 on 2026-03-02 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_type', models.CharField(choices=[('regulatory', 'Regulatory'), ('harvest_forecast', 'Harvest Forecast')], max_length=20)),
                ('query_text', models.TextField()),
                ('species', models.CharField(blank=True, max_length=20, null=True)),
                ('molecule', models.CharField(blank=True, max_length=100, null=True)),
                ('response_text', models.TextField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('source_citation', models.CharField(blank=True, max_length=500, null=True)),
                ('flagged_for_review', models.BooleanField(default=False)),
                ('retrieved_chunk_ids', models.JSONField(default=list)),
                ('model_version', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
