# Generated by Django 4.2.27 on 2026-01-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('vet', 'Vet'), ('regulator', 'Regulator')], default='farmer', max_length=20),
        ),
    ]
