# Generated by Django 4.2.27 on 2026-02-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_address_user_district_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('vet', 'Vet'), ('data_operator', 'Data operator'), ('regulator', 'Regulator')], default='data_operator', max_length=20),
        ),
    ]
