# Generated by Django 4.2.27 on 2026-01-20 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('farm_number', models.CharField(max_length=100)),
                ('farm_type', models.CharField(choices=[('backyard', 'Backyard'), ('commercial', 'Commercial')], max_length=20)),
                ('species_type', models.CharField(choices=[('avian', 'Avian (Poultry/Birds)'), ('bovine', 'Bovine (Cattle)'), ('suine', 'Suine (Pigs/Swine)'), ('caprine', 'Caprine (Goats)'), ('ovine', 'Ovine (Sheep)')], max_length=20)),
                ('total_animals', models.IntegerField()),
                ('avg_weight', models.FloatField(help_text='Average weight in kg')),
                ('avg_feed_consumption', models.FloatField(help_text='Average feed consumption in kg/day')),
                ('avg_water_consumption', models.FloatField(help_text='Average water consumption in litres/day')),
                ('antibiotic_used', models.BooleanField(default=False)),
                ('antibiotic_name', models.CharField(blank=True, choices=[('spectromycin', 'Spectromycin')], max_length=50, null=True)),
                ('antibiotic_reason', models.CharField(blank=True, choices=[('treat_disease', 'Treat Disease'), ('prophylactic', 'Prophylactic'), ('other', 'Other')], max_length=20, null=True)),
                ('treated_for', models.CharField(blank=True, choices=[('enteric', 'Enteric'), ('respiratory', 'Respiratory'), ('reproductive', 'Reproductive')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='users.user')),
            ],
        ),
    ]
