# Generated by Django 4.2.27 on 2026-01-21 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='antibiotic_name',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='antibiotic_reason',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='antibiotic_used',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='treated_for',
        ),
    ]
