# Generated by Django 4.2.27 on 2026-01-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_remove_farm_antibiotic_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='species_type',
            field=models.CharField(choices=[('AVI', 'Avian (Poultry/Birds)'), ('BOV', 'Bovine (Cattle)'), ('SUI', 'Suine (Pigs/Swine)'), ('CAP', 'Caprine (Goats)'), ('OVI', 'Ovine (Sheep)'), ('EQU', 'Equine (Horses)'), ('LEP', 'Leporine (Rabbits)'), ('PIS', 'Pisces (Fish)'), ('CAM', 'Camelids (Camels)'), ('API', 'Apiculture (Bees)')], max_length=20),
        ),
    ]
