# Generated by Django 4.2.27 on 2026-01-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_alter_farm_species_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
