# Generated by Django 4.2.27 on 2026-02-18 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_role'),
        ('farms', '0005_alter_farm_village'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_tag', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flock_tag', models.CharField(max_length=50)),
                ('species_type', models.CharField(choices=[('AVI', 'Avian (Poultry/Birds)'), ('BOV', 'Bovine (Cattle)'), ('SUI', 'Suine (Pigs/Swine)'), ('CAP', 'Caprine (Goats)'), ('OVI', 'Ovine (Sheep)'), ('EQU', 'Equine (Horses)'), ('LEP', 'Leporine (Rabbits)'), ('PIS', 'Pisces (Fish)'), ('CAM', 'Camelids (Camels)'), ('API', 'Apiculture (Bees)')], max_length=20)),
                ('size', models.IntegerField()),
                ('age_in_weeks', models.IntegerField(blank=True, null=True)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flocks', to='farms.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owners_created', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('date_reported', models.DateField(auto_now_add=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='farms.animal')),
                ('flock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='farms.flock')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='farms.owner')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems_reported', to='users.user')),
            ],
        ),
        migrations.AddField(
            model_name='flock',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flocks', to='farms.owner'),
        ),
        migrations.AddField(
            model_name='animal',
            name='flock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='farms.flock'),
        ),
        migrations.AddField(
            model_name='farm',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farms', to='farms.owner'),
        ),
        migrations.AlterUniqueTogether(
            name='flock',
            unique_together={('owner', 'flock_tag')},
        ),
        migrations.AlterUniqueTogether(
            name='animal',
            unique_together={('flock', 'animal_tag')},
        ),
    ]
