# Generated by Django 4.2.27 on 2026-02-25 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_dataoperator'),
        ('farms', '0006_animal_flock_owner_problem_flock_owner_animal_flock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='user',
            field=models.ForeignKey(help_text='The Data Operator or user managing this farm', on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='users.user'),
        ),
    ]
