# Generated by Django 4.2.27 on 2026-02-25 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0007_alter_farm_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='district',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='state',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='village',
        ),
        migrations.AddField(
            model_name='owner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='farms.owner'),
            preserve_default=False,
        ),
    ]
