# Generated by Django 4.2.27 on 2026-02-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0008_remove_owner_district_remove_owner_state_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='flock',
            name='flock_code',
            field=models.CharField(blank=True, help_text='Short alphanumeric code, unique per farm (e.g. FLK01)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_tag',
            field=models.CharField(help_text='Auto-generated: farm_number-flock_code-NNN', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='avg_feed_consumption',
            field=models.FloatField(default=0.0, help_text='Average feed consumption in kg/day'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='avg_water_consumption',
            field=models.FloatField(default=0.0, help_text='Average water consumption in litres/day'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='avg_weight',
            field=models.FloatField(default=0.0, help_text='Average weight in kg'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='species_type',
            field=models.CharField(blank=True, choices=[('AVI', 'Avian (Poultry/Birds)'), ('BOV', 'Bovine (Cattle)'), ('SUI', 'Suine (Pigs/Swine)'), ('CAP', 'Caprine (Goats)'), ('OVI', 'Ovine (Sheep)'), ('EQU', 'Equine (Horses)'), ('LEP', 'Leporine (Rabbits)'), ('PIS', 'Pisces (Fish)'), ('CAM', 'Camelids (Camels)'), ('API', 'Apiculture (Bees)')], help_text='Primary species (optional — use flocks for multi-species)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='total_animals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flock',
            name='flock_tag',
            field=models.CharField(blank=True, help_text='Composite tag: farm_number-flock_code (auto-generated)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flock',
            name='size',
            field=models.IntegerField(help_text='Number of animals in this flock'),
        ),
        migrations.AlterUniqueTogether(
            name='flock',
            unique_together={('farm', 'flock_code')},
        ),
    ]
