# Generated by Django 4.2.27 on 2026-02-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0009_bulk_flock_and_treatment_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='species_type',
            field=models.CharField(blank=True, choices=[('AVI', 'Avian (Poultry/Birds)'), ('BOV', 'Bovine (Cattle)'), ('SUI', 'Suine (Pigs/Swine)'), ('CAP', 'Caprine (Goats)'), ('OVI', 'Ovine (Sheep)'), ('EQU', 'Equine (Horses)'), ('LEP', 'Leporine (Rabbits)'), ('PIS', 'Pisces (Fish)'), ('CAM', 'Camelids (Camels)'), ('API', 'Apiculture (Bees)'), ('MIX', 'Mixed (Multi-species)')], help_text='Primary species (optional — use flocks for multi-species)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='flock',
            name='species_type',
            field=models.CharField(choices=[('AVI', 'Avian (Poultry/Birds)'), ('BOV', 'Bovine (Cattle)'), ('SUI', 'Suine (Pigs/Swine)'), ('CAP', 'Caprine (Goats)'), ('OVI', 'Ovine (Sheep)'), ('EQU', 'Equine (Horses)'), ('LEP', 'Leporine (Rabbits)'), ('PIS', 'Pisces (Fish)'), ('CAM', 'Camelids (Camels)'), ('API', 'Apiculture (Bees)'), ('MIX', 'Mixed (Multi-species)')], max_length=20),
        ),
    ]
