# Generated by Django 4.2.27 on 2026-02-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0010_alter_farm_species_type_alter_flock_species_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='flock',
            name='avg_feed_consumption',
            field=models.FloatField(default=0.0, help_text='Average feed consumption in kg/day'),
        ),
        migrations.AddField(
            model_name='flock',
            name='avg_water_consumption',
            field=models.FloatField(default=0.0, help_text='Average water consumption in litres/day'),
        ),
        migrations.AddField(
            model_name='flock',
            name='avg_weight',
            field=models.FloatField(default=0.0, help_text='Average weight in kg'),
        ),
    ]
