# Generated by Django 4.2.27 on 2026-02-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0011_flock_avg_feed_consumption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flock',
            name='age_in_weeks',
        ),
        migrations.AddField(
            model_name='flock',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Calculated birth date for rolling age updates', null=True),
        ),
        migrations.AddField(
            model_name='flock',
            name='initial_age_in_weeks',
            field=models.IntegerField(blank=True, help_text='Age at the time of registration', null=True),
        ),
    ]
